# Generated by Django 4.0.2 on 2022-03-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('created_Date', models.DateField()),
                ('owner', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('is_Published', models.CharField(max_length=10)),
            ],
        ),
    ]
